version: "3.7"
services:
  vending-hub-web:
    ## A imagem deve ter sido criada manualmente com: docker build -t vending-admin-hub:latest .
    image: vending-admin-hub:latest 
    
    networks:
      - akiernet

    environment:
      - VITE_SUPABASE_PROJECT_ID=${VITE_SUPABASE_PROJECT_ID}
      - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      
      labels:
        - "traefik.enable=true"
        
        ## Configuração do Roteador (Domínio)
        - "traefik.http.routers.vending-hub-web.rule=Host(`app.akier.com.br`)"
        - "traefik.http.routers.vending-hub-web.entrypoints=websecure"
        - "traefik.http.routers.vending-hub-web.priority=1"
        
        ## Configuração SSL (Let's Encrypt igual ao padrão Orion)
        - "traefik.http.routers.vending-hub-web.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.vending-hub-web.service=vending-hub-web"
        
        ## Aponta para a porta 80 (onde o NGINX expõe a aplicação dentro do container)
        - "traefik.http.services.vending-hub-web.loadbalancer.server.port=80"
        - "traefik.http.services.vending-hub-web.loadbalancer.passHostHeader=1"



networks:
  akiernet:
    external: true
    name: akiernet