// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajwwhmxhsmylkxslodiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqd3dobXhoc215bGt4c2xvZGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTQ0MTAsImV4cCI6MjA3MTQ3MDQxMH0.sonIMKxd8pFJRbjZ8lSc7yKR0uGKT3VgztHnQTnW97s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});